analysis/urls.py
from __future__ import absolute_import, unicode_literals

from django.urls import path

from . import views

urlpatterns = [
    path('public-groups/', views.PublicAnalysisGroupListView.as_view(), name='public-group-list'),
    path('group/create/', views.AnalysisGroupCreate.as_view(), name='group-create'),
    path('group/<int:pk>/edit/', views.AnalysisGroupUpdate.as_view(), name='group-edit'),
    path('group/<int:pk>/delete/', views.AnalysisGroupDelete.as_view(), name='group-delete'),
    path('group/<int:pk>/individual-analysis/', views.IndividualAnalysis.as_view(), name='individual-analysis'),
    path('group/<int:pk>/relay-analysis/', views.RelayAnalysis.as_view(), name='relay-analysis'),
    path('analyse/create-fastest-setups/', views.create_fastest_setups, name='create-setups'),
]

lifesaving_rankings/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from analysis.views import ExtraTimesListView, AnalysisGroupListView
from . import views
from .views import Account, Home

urlpatterns = [
    path('', Home.as_view(), name='home'),

    path('about/', views.about, name='about'),
    path('changelog/', views.changelog, name='changelog'),
    path('ultimate-lifesaver/', views.ultimate_lifesaver),

    path('', include('rankings.urls')),
    path('analysis/', include('analysis.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),

    path('rankings<path:path>', views.rankings_redirect),
    path('accounts/details/', Account.as_view(), name='account'),
    path('accounts/extra-times/', ExtraTimesListView.as_view(), name='extra-times-list'),
    path('accounts/analysis-groups/', AnalysisGroupListView.as_view(), name='private-group-list'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

handler404 = 'lifesaving_rankings.views.error_404_view'
handler500 = 'lifesaving_rankings.views.error_500_view'

analysis/models.py
from datetime import timedelta

from django.db import models
from django.db.models import ForeignKey, Count

from rankings.models import Event, Athlete
from django.contrib.auth.models import User

from rankings.templatetags.datetime_filter import format_time


class SpecialResultGroup(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class SpecialResult(models.Model):
    event = ForeignKey(Event, on_delete=models.CASCADE)
    time = models.DurationField()
    special_result_group = models.ForeignKey(SpecialResultGroup, on_delete=models.CASCADE, null=True)

    def __str__(self):
        if self.special_result_group:
            return self.special_result_group.name + ': ' + self.event.name
        return self.event.name

    def time_formatted(self):
        return format_time(self.time)


class AnalysisGroup(models.Model):
    name = models.CharField(max_length=60)
    creator = ForeignKey(User, on_delete=models.SET_NULL, null=True)
    public = models.BooleanField(default=False)
    athletes = models.ManyToManyField(Athlete)
    simulation_in_progress = models.BooleanField(default=False)
    simulation_date_from = models.DateField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('pk',)

    def get_group_teams_with_full_setup(self):
        num_events = Event.objects.filter(type=Event.RELAY_COMPLETE).count()
        group_teams = GroupTeam.objects.annotate(num_setups=Count('setups')).filter(num_setups=num_events,
                                                                                    analysis_group=self).all()
        return group_teams

    def count_group_teams_without_full_setup(self):
        num_events = Event.objects.filter(type=Event.RELAY_COMPLETE).count()
        group_team_count = GroupTeam.objects.annotate(num_setups=Count('setups')).filter(num_setups__lt=num_events) \
            .filter(analysis_group=self).count()
        return group_team_count

    def delete_all_previous_analysis(self):
        group_teams = GroupTeam.objects.filter(analysis_group=self)
        for group_team in group_teams:
            setups = group_team.setups.all()
            setups.delete()
        group_teams.delete()

    relay_analysis_is_available = None

    def relay_analysis_available(self):
        if self.relay_analysis_is_available is None:
            group_teams = list(self.groupteam_set.all().order_by('analysis_group__groupteam'))
            if len(group_teams) == 0:
                self.relay_analysis_is_available = False
                return self.relay_analysis_is_available
            last_group_team = group_teams[-1]
            self.relay_analysis_is_available = len(list(last_group_team.setups.all())) > 0
        return self.relay_analysis_is_available

    def clean_teams(self):
        self.remove_unused_athletes_from_teams()
        self.delete_duplicate_teams()

    def remove_unused_athletes_from_teams(self):
        for group_team in self.groupteam_set.all():
            group_team.remove_unused_athletes()

    def delete_duplicate_teams(self):
        for group_team in self.groupteam_set.all():
            qs = self.groupteam_set.exclude(pk=group_team.pk)
            qs = qs.annotate(athlete_count=Count('athletes')).filter(athlete_count=group_team.athletes.count())
            for athlete in group_team.athletes.all():
                qs = qs.filter(athletes__pk=athlete.pk)
            qs.delete()


class GroupEventSetup(models.Model):
    athletes = models.ManyToManyField(Athlete, through='GroupEvenSetupSegment')
    event = ForeignKey(Event, on_delete=models.CASCADE)
    time = models.DurationField()

    def get_athletes_ordered_by_index(self):
        return self.athletes.all().order_by('groupevensetupsegment__index')


class GroupEvenSetupSegment(models.Model):
    athlete = ForeignKey(Athlete, on_delete=models.CASCADE)
    group_event_setup = ForeignKey(GroupEventSetup, on_delete=models.CASCADE)
    index = models.IntegerField()


class GroupTeam(models.Model):
    analysis_group = ForeignKey(AnalysisGroup, on_delete=models.SET_NULL, null=True)
    athletes = models.ManyToManyField(Athlete)
    setups = models.ManyToManyField(GroupEventSetup)

    def get_total_time(self):
        setups = self.setups.all()
        total_time = timedelta(0)
        for setup in setups:
            total_time += setup.time
        return total_time

    def get_ordered_setups(self):
        return self.setups.order_by('event')

    def get_used_athletes(self):
        setups = self.setups.all()
        setup_segments = GroupEvenSetupSegment.objects.filter(group_event_setup__in=setups)
        athletes = Athlete.objects.filter(groupevensetupsegment__in=setup_segments).distinct()
        return athletes

    def get_unused_athletes(self):
        used_athletes = self.get_used_athletes()
        all_athletes = self.athletes.all()
        return list(set(all_athletes) - set(used_athletes))

    def remove_unused_athletes(self):
        for unused_athlete in self.get_unused_athletes():
            self.athletes.remove(unused_athlete)

analysis/views.py
import functools
import itertools
from datetime import timedelta
from multiprocessing import Process
from time import sleep
import requests
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.models import Site
from django.core.exceptions import PermissionDenied
from django.db.models import Min, Q
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from django_tables2 import SingleTableMixin, SingleTableView

from analysis.forms import ChooseFromDateForm, AnalysisGroupForm
from analysis.models import AnalysisGroup, GroupTeam, GroupEventSetup, GroupEvenSetupSegment, \
    SpecialResultGroup
from analysis.tables import ExtraTimesTable, AnalysisGroupTable
from rankings.models import Event, Athlete, IndividualResult, RelayOrder


def get_top_results_by_athlete(gender=None, athletes=None, date=None, user=None):
    events = Event.objects.filter(type=Event.INDIVIDUAL, use_points_in_athlete_total=True).order_by('id')
    if athletes is None:
        athletes = Athlete.objects.filter(gender=gender)
    results = {}

    for athlete in athletes:
        individual_results = []
        for event in events:
            qs = IndividualResult.objects.filter(athlete=athlete, event=event, did_not_start=False, disqualified=False)
            if user is not None:
                qs = qs.filter(Q(extra_analysis_time_by=user) | Q(extra_analysis_time_by=None))
            if date is not None:
                qs = qs.filter(competition__date__gte=date)
            qs = qs.order_by('time')
            individual_results.append(qs.first())
        results[athlete.id] = individual_results
    return results


class AnalysisGroupListView(LoginRequiredMixin, SingleTableView):
    model = AnalysisGroup
    template_name = 'analysisgroup_list_private.html'
    table_class = AnalysisGroupTable
    ordering = ['pk']
    table_pagination = {
        "per_page": 10
    }

    def get_queryset(self):
        user = self.request.user
        qs = super(AnalysisGroupListView, self).get_queryset()
        qs = qs.filter(creator=user)
        return qs


class PublicAnalysisGroupListView(SingleTableView):
    model = AnalysisGroup
    table_class = AnalysisGroupTable
    ordering = ['pk']
    template_name = 'analysisgroup_list.html'

    def get_queryset(self):
        qs = super(PublicAnalysisGroupListView, self).get_queryset().order_by('pk')
        qs = qs.filter(public=True)
        return qs

    def get_context_data(self, **kwargs):
        context = super(PublicAnalysisGroupListView, self).get_context_data()
        context['public'] = True
        return context


class AnalysisGroupUpdate(LoginRequiredMixin, UpdateView):
    model = AnalysisGroup
    form_class = AnalysisGroupForm
    success_url = reverse_lazy('private-group-list')
    template_name = 'analysisgroup_form.html'

    def get_object(self, queryset=None):
        obj = super(AnalysisGroupUpdate, self).get_object()
        if obj.creator != self.request.user:
            raise PermissionDenied
        else:
            return obj


class AnalysisGroupDelete(LoginRequiredMixin, DeleteView):
    model = AnalysisGroup
    success_url = reverse_lazy('private-group-list')
    template_name = 'analysisgroup_confirm_delete.html'

    def get_object(self, queryset=None):
        obj = super(AnalysisGroupDelete, self).get_object()
        if obj.creator != self.request.user:
            raise PermissionDenied
        else:
            return obj


class AnalysisGroupCreate(LoginRequiredMixin, CreateView):
    model = AnalysisGroup
    form_class = AnalysisGroupForm
    success_url = reverse_lazy('private-group-list')
    template_name = 'analysisgroup_form.html'

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super(AnalysisGroupCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(AnalysisGroupCreate, self).get_context_data()
        context['new_group'] = True
        return context


class IndividualAnalysis(TemplateView):
    template_name = 'individual_analysis.html'

    def get_context_data(self, **kwargs):
        context = super(IndividualAnalysis, self).get_context_data(**kwargs)
        analysis_group = AnalysisGroup.objects.get(pk=self.kwargs.get('pk'))
        if not analysis_group.public and analysis_group.creator != self.request.user and not self.request.user.is_superuser:
            raise PermissionDenied

        date = None
        form = ChooseFromDateForm(self.request.GET)
        if form.is_valid():
            date = form.cleaned_data['from_date']
        if form is None:
            context['form'] = ChooseFromDateForm()
        else:
            context['form'] = form

        context['results'] = get_top_results_by_athlete(athletes=analysis_group.athletes.all(), date=date, user=analysis_group.creator)
        context['events'] = Event.objects.filter(type=Event.INDIVIDUAL, use_points_in_athlete_total=True).order_by('id')
        context['analysis_group'] = analysis_group
        context['special_result_groups'] = SpecialResultGroup.objects.all()
        context['world_records_women'] = get_world_records(Athlete.FEMALE)
        context['world_records_men'] = get_world_records(Athlete.MALE)
        return context


def get_world_records(gender):
    world_records = []
    for event in Event.objects.filter(use_points_in_athlete_total=True).all():
        world_records.append(IndividualResult.public_objects.filter(athlete__gender=gender, event=event).order_by('time').first())
    return world_records


class RelayAnalysis(TemplateView):
    template_name = "relay_analysis.html"

    def post(self, *args, **kwargs):
        analysis_group = AnalysisGroup.objects.get(pk=self.kwargs.get('pk'))

        if analysis_group.creator != self.request.user:
            return HttpResponse('Unauthorized', status=401)

        form = ChooseFromDateForm(self.request.POST)
        date = None
        if form.is_valid():
            date = form.cleaned_data['from_date']

        if analysis_group.athletes.count() <= 10 and not analysis_group.simulation_in_progress:
            analysis_group.simulation_date_from = date
            create_combinations(analysis_group)
            analysis_group.simulation_in_progress = True
            analysis_group.save()
            return redirect('relay-analysis', analysis_group.id)

    def get_context_data(self, **kwargs):
        context = super(RelayAnalysis, self).get_context_data(**kwargs)
        analysis_group = AnalysisGroup.objects.get(pk=self.kwargs.get('pk'))
        if not analysis_group.public and analysis_group.creator != self.request.user and not self.request.user.is_superuser:
            raise PermissionDenied

        context['form'] = ChooseFromDateForm(required=False)
        context['events'] = Event.objects.filter(type=Event.RELAY_COMPLETE).order_by('pk').all()
        context['analysis_group'] = analysis_group
        context['group_teams'] = analysis_group.get_group_teams_with_full_setup()
        groupteam_count = analysis_group.groupteam_set.count()
        context['progress'] = 0
        if groupteam_count > 0:
            context['progress'] = context['group_teams'].count() / analysis_group.groupteam_set.count() * 100
        return context


def create_combinations(analysis_group):
    analysis_group.delete_all_previous_analysis()
    athletes = analysis_group.athletes.all()
    possible_teams = itertools.combinations(athletes, 6)

    group_teams = map(functools.partial(create_group_teams, analysis_group), possible_teams)
    group_teams = list(group_teams)
    last_group_team = group_teams[-1]
    first_group_team = next(iter(group_teams or []), None)

    params = {'current_group_team': first_group_team.id, 'last_group_team': last_group_team.id,
              'analysis_group': analysis_group.id}

    current_site = Site.objects.get_current()
    url = current_site.domain + str(reverse_lazy('create-setups'))

    p = Process(target=async_request, args=(url, params))
    p.daemon = True
    p.start()


def create_fastest_setups(request):
    if 'current_group_team' not in request.GET or 'last_group_team' not in request.GET or 'analysis_group' not in request.GET:
        return HttpResponseBadRequest
    analysis_group = AnalysisGroup.objects.get(pk=request.GET['analysis_group'])
    if not GroupTeam.objects.filter(pk=request.GET['current_group_team']).exists():
        analysis_group.simulation_in_progress = False
        analysis_group.save()
        analysis_group.clean_teams()
        return HttpResponseBadRequest

    last_group_team = GroupTeam.objects.get(pk=request.GET['last_group_team'])
    current_group_team = GroupTeam.objects.get(pk=request.GET['current_group_team'])
    events = Event.objects.filter(type=Event.RELAY_COMPLETE)
    for event in events:
        get_fastest_time_for_team_and_event(current_group_team, event, analysis_group)

    if last_group_team.id is not current_group_team.id:
        params = {'current_group_team': current_group_team.id + 1, 'last_group_team': last_group_team.id,
                  'analysis_group': analysis_group.id}

        current_site = Site.objects.get_current()
        url = current_site.domain + str(reverse_lazy('create-setups'))

        p = Process(target=async_request, args=(url, params))
        p.daemon = True
        p.start()
        sleep(1)
    else:
        analysis_group.clean_teams()
        analysis_group.simulation_in_progress = False
        analysis_group.save()

    return HttpResponse()



analysis/templates/analysisgroup_confirm_delete.html
{% extends "base.html" %}
{% load datetime_filter %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete this group?</p>

        <p>
            Name: {{ object.name }}<br>
            Athletes:
        </p>
        <ul>
            {% for athlete in object.athletes.all %}
                <li>{{ athlete.name }}</li>
            {% endfor %}
        </ul>

        <input type="submit" value="Delete" class="ui button red">
    </form>
{% endblock %}

analysis/templates/analysisgroup_form.html
{% extends "base.html" %}
{% load widget_tweaks django_bootstrap_breadcrumbs styled_fields %}

{% block head_title %}
    {% if new_group %}
        Create a new group
    {% else %}
        Edit group
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Analysis" "public-group-list" %}
    {% if new_group %}
        {% breadcrumb "Create" "group-create" %}
    {% else %}
        {% with label="Edit"|add:" '"|add:analysisgroup.name|add:"'" %}
            {% breadcrumb label "group-edit" analysisgroup.id %}
        {% endwith %}
    {% endif %}

    {% render_breadcrumbs "breadcrumbs.html" %}
{% endblock %}

{% block content %}
    <h1>
        {% if new_group %}
            Create a new group
        {% else %}
            Edit group
        {% endif %}
    </h1>

    <form action="" method="post" class="ui narrow form">{% csrf_token %}

        {% styled_fields form %}

        <div class="ui buttons">
            <a href="{% url "private-group-list" %}" class="ui button">
                Cancel
            </a>
            <div class="or"></div>
            <button class="ui positive button" type="submit">
                {% if new_group %}Create{% else %}Update{% endif %}
            </button>
        </div>

    </form>
{% endblock %}

analysis/templates/analysisgroup_list.html
{% extends "base.html" %}
{% load django_tables2 %}
{% load django_bootstrap_breadcrumbs %}

{% block head_title %}Public groups{% endblock %}

{% block breadcrumbs %}

    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Analysis" "public-group-list" %}

    {% render_breadcrumbs "breadcrumbs.html" %}

{% endblock %}

{% block content %}
    <h1>Public groups</h1>

    <a href="{% url 'private-group-list' %}" class="ui button">
        Go to My Groups
    </a>

    <a href="{% url 'group-create' %}" class="ui right floated left labeled primary icon button">
        <i class="plus square icon"></i>
        Create a group
    </a>

    <br><br>

    {% render_table table %}

{% endblock %}

analysis/templates/analysisgroup_list_private.html
{% extends "account.html" %}
{% load django_tables2 %}
{% load django_bootstrap_breadcrumbs %}

{% block head_title %}My groups{% endblock %}

{% block breadcrumbs %}

    {% breadcrumb "Home" "/" %}
    {% breadcrumb "My Account" "account" %}
    {% breadcrumb "My analysis groups" "private-group-list" %}

    {% render_breadcrumbs "breadcrumbs.html" %}

{% endblock %}

{% block account_content %}
    <h1>My analysis groups</h1>
    <a href="{% url 'public-group-list' %}" class="ui button">
        Go to Public Groups
    </a>

    <a href="{% url 'group-create' %}" class="ui right floated left labeled primary icon button">
        <i class="plus square icon"></i>
        Create a group
    </a>

    <br><br>

    {% render_table table %}

{% endblock %}

analysis/templates/extra_times_list.html
{% extends "account.html" %}

{% load i18n styled_fields django_bootstrap_breadcrumbs %}
{% load render_table from django_tables2 %}

{% block head_title %}Extra times{% endblock %}

{% block breadcrumbs %}

    {% breadcrumb "Home" "/" %}
    {% breadcrumb "My Account" "account" %}
    {% breadcrumb "My extra times" "extra-times-list" %}

    {% render_breadcrumbs "breadcrumbs.html" %}

{% endblock %}

{% block account_content %}
    <h1>Extra times</h1>
    <p>These extra times are added by you and are <strong>only</strong> visible in analysis groups created by you.</p>
    <p>To add an extra time, go to an athlete and click on <i>Add extra time</i>.</p>
    {% render_table table %}
{% endblock %}

analysis/templates/individual_analysis.html
{% extends "base.html" %}
{% load datetime_filter django_bootstrap_breadcrumbs %}
{% load id_to_athlete_name %}
{% load id_to_slug %}
{% load widget_tweaks %}
{% block head_title %}Individual analysis{% endblock %}

{% block breadcrumbs %}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Analysis" "public-group-list" %}
    {% with page_name=analysis_group.name|add:" "|add:"individual analysis" %}
        {% breadcrumb page_name "individual-analysis" analysis_group.id %}
    {% endwith %}

    {% render_breadcrumbs "breadcrumbs.html" %}
{% endblock %}

{% block content %}
    <div class="ui stackable grid">
        <div class="ui twelve wide column">
            <h1 class="ui header">Individual Analysis: {{ analysis_group.name }}</h1>
        </div>
        <div class="ui four wide column">
            {% if request.user == analysis_group.creator %}
                <a href="{% url 'group-edit' analysis_group.id %}">
                    <button class="ui labeled icon button right floated">
                        <i class="edit icon"></i>Edit this group
                    </button>
                </a>
            {% endif %}
        </div>
    </div>

    <br>

    <div class="ui styled fluid accordion">
        <div class="title"><i class="dropdown icon"></i>Explanation</div>
        <div class="content">
            Individual Analysis tries to answer the following question: which athlete in a group has the best potential to swim a given time?<br>
            In the grid below, all athletes in the group are displayed with their best time per event. You can choose to ignore older results by using the filter option.<br>
            In the top row there are multiple input fields for times with which you want to compare your athletes. You can also preset these fields with one of the sets using the dropdown on the left of these input fields.<br>
            If you change these fields you'll see that the colors of the athlete's times change. This is based on how close they are compared to the time you specified:
            <ul>
                <li>Green: within 100%, so faster then the given time</li>
                <li>Orange: between 100% and 105% of the given time</li>
                <li>Red: slower then 105% of the given time</li>
            </ul>
        </div>
    </div>

    <br>

    <form action="" method="get" class="ui form input filter">{% csrf_token %}
        <div class="fields">
            <div class="field">
                <label>{{ form.from_date.label }}</label>
                <div class="ui date calendar">
                    <div class="ui input left icon">
                        <i class="calendar icon"></i>
                        {{ form.from_date }}
                    </div>
                </div>
            </div>
            <div class="field">
                <button class="ui submit primary button" type="submit">Filter</button>
            </div>
        </div>
    </form>

    <table class="ui celled table" id="analysis-table">

        <thead>
        <tr>
            <th>Name</th>
            {% for event in events %}
                <th>
                    {{ event.name }}
                </th>
            {% endfor %}
        </tr>
        </thead>

        <tbody>

        <tr>
            <td>
                <select class="ui default dropdown" id="special-result-set">
                    <option value="">Comparison sets</option>
                    {% for special_result_group in special_result_groups %}
                        <option value="{% for special_result in special_result_group.specialresult_set.all %}'{{ special_result.event.pk }}': '{{ special_result.time|format_time }}'{% if not forloop.last %},{% endif %}{% endfor %}">
                            {{ special_result_group.name }}
                        </option>
                    {% endfor %}
                    <option value="{% for world_record in world_records_women %}'{{ world_record.event.pk }}': '{{ world_record.time|format_time }}'{% if not forloop.last %},{% endif %}{% endfor %}">
                        World Records women
                    </option>
                    <option value="{% for world_record in world_records_men %}'{{ world_record.event.pk }}': '{{ world_record.time|format_time }}'{% if not forloop.last %},{% endif %}{% endfor %}">
                        World Records men
                    </option>
                </select>
            </td>
            {% for event in events %}
                <td class="special-result" data-event-id="{{ event.id }}">
                    <div class="ui time input">
                        <input type="text" placeholder="0:00.00">
                    </div>
                </td>
            {% endfor %}
        </tr>

        {% for athlete_id, qs in results.items %}
            <tr>
                <td>
                    <a href="{% url 'athlete-detail' athlete_id|id_to_slug %}">
                        {{ athlete_id|id_to_athlete_name }}
                    </a>
                </td>
                {% for result in qs %}
                    {% if result %}
                        <td class="analysis-time" data-event-id="{{ result.event.pk }}">
                            {{ result.time|format_time }}<sup class="percentage"></sup>
                            {% if result.extra_analysis_time_by is not None %}
                                <span data-content="This time was added by the group's creator">
                                    <i class="attention grey icon"></i>
                                </span>
                            {% endif %}
                        </td>
                    {% else %}
                        <td></td>
                    {% endif %}
                {% endfor %}
            </tr>
        {% endfor %}

        </tbody>

    </table>
{% endblock %}

{% block javascript_after %}
    <script>
        $(document).ready(function () {
            $('.special-result input').trigger('change');
        });
    </script>
{% endblock %}